---

############
# Apt
############

letsencrypt_email: ''

############
# Users
############

users:
  - name: john
    initial_password: secret
    use_root_ssh_key: true
    copy_ssh_key: true
    copy_ssh_key_path: /root/.ssh/authorized_keys

############
# SSL
############
ssl_enabled: false

############
# UFW
############

ftp_enabled: true

############
# Nginx
############

web_user: www-data
web_group: www-data
web_root: /var/www/example/public

server_name: example.com

############
# Git
############

github_repo: git@github.com:llaski/laravel-server-provisioning-example.git
git_user: john
github_config_email: 'john@example.com'
github_config_name:  'John'
project_root: /var/www/example

############
# Laravel Environment Variables
############

app_name: Laravel
app_env: production
app_debug: false
app_log_level: debug
app_key: "base64:p1YXT8fxSfmghgSDW92lDNjytZ13QwVKABxgqKD/vd4="
app_url: http://example.com
db_connection: mysql
db_host: 127.0.0.1
db_database: example
db_username: root
db_password: root
broadcast_driver: log
cache_driver: file
session_driver: file
queue_driver: sync
mail_driver: smtp
mail_host: smtp.mailtrap.io
mail_port: 2525
mail_username: null
mail_password: null
mail_encryption: null
mail_from: 'john@example.com'
mail_name: 'John'
