---

############
# Apt
############

letsencrypt_email: ''

############
# Users
############

user_name: larry
initial_user_password: secret

############
# SSL
############
ssl_enabled: false

############
# UFW
############

ftp_enabled: true

############
# Nginx
############

web_user: www-data
web_group: web
web_root: /var/www/example/public

server_name: example.com

############
# Git
############

github_repo: git@github.com:llaski/laravel-server-provisioning.git
github_config_email: ''
github_config_name: ''

############
# Laravel Environment Variables
############

app_name: Laravel
app_env: production
app_debug: false
app_log_level: debug
app_url: https://example.com
db_host: 127.0.0.1
db_database: example
db_username: root
db_password: root
db_port: 3306
broadcast_driver: log
cache_driver: file
session_driver: file
queue_driver: sync
mail_driver: smtp
mail_host: smtp.mailtrap.io
mail_port: 2525
mail_username: null
mail_password: null
mail_encryption: null
