---

- include: remove-apache.yml

- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install Nginx
  when: ppastable|success
  apt: pkg=nginx state=latest update_cache=true
  register: nginxinstalled
  notify:
    - Start Nginx

- name: Get PHP Version
  include_vars: file="../../php/defaults/main.yml"

- name: Add H5BP Config
  copy: src=h5bp dest=/etc/nginx owner=root group=root

- name: Disable Default Config
  file: dest=/etc/nginx/sites-enabled/default state=absent
  notify:
    - Reload Nginx

- name: Replace Main Nginx Config
  copy: src=templates/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=644 backup=yes
  notify:
    - Reload Nginx

- name: Add {{ server_name }} Config
  template: src={{ server_name }}.conf.j2 dest=/etc/nginx/sites-available/{{ server_name }} owner=root group=root

- name: Enable Site Config
  file: src=/etc/nginx/sites-available/{{ server_name }} dest=/etc/nginx/sites-enabled/{{ server_name }} state=link
  notify:
    - Reload Nginx

- name: Create Site Directory
  file: path={{ project_root }} state=directory mode=775 owner=www-data group=www-data recurse=yes
