---
- name: Install Nginx
  apt: name=nginx state=installed update_cache=true
  register: nginxinstalled
  notify:
    - Start Nginx

- name: Add H5BP Config
  copy: src=h5bp dest=/etc/nginx owner=root group=root

- name: Disable Default Config
  file: dest=/etc/nginx/sites-enabled/default state=absent
  notify:
    - Reload Nginx

- name: Replace Main Nginx Config
  copy: src=templates/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=644 backup=yes
  notify:
    - Reload Nginx

- name: Add {{ server_name }} Config
  when: nginxinstalled|success
  template: src={{ server_name }}.conf.j2 dest=/etc/nginx/sites-available/{{ server_name }} owner=root group=root

- name: Enable Site Config
  file: src=/etc/nginx/sites-available/{{ server_name }} dest=/etc/nginx/sites-enabled/{{ server_name }} state=link
  notify:
    - Reload Nginx

- name: Create Site Directory
  file: path=/var/www/{{ server_name }} state=directory mode=775 owner=www-data group=www-data recurse=yes

# - include: crontab.yml
#   when: nginx_ssl_params_installed|success
