---

- include: remove-apache.yml

- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install Nginx
  when: ppastable|success
  apt: pkg=nginx state=latest update_cache=true
  register: nginxinstalled
  notify:
    - Start Nginx

- name: Add H5BP Config
  copy: src=h5bp dest=/etc/nginx owner=root group=root

- name: Disable Default Config
  file: dest=/etc/nginx/sites-enabled/default state=absent
  notify:
    - Reload Nginx

- name: Replace Main Nginx Config
  copy: src=templates/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=644 backup=yes
  notify:
    - Reload Nginx

- name: Ensure {{ sites_root }} Directory has correct permissions, user and group
  file: path={{ sites_root }} state=directory owner=www-data group=www-data mode=0755

- name: Create {{ project_root }} Directory
  file: path={{ project_root }} state=directory owner=www-data group=www-data recurse=yes

#This will check if SSL is set up, and if not set it up the first time
- name: Check SSL Full Chain File Exists
  when: ssl_enabled
  stat: path=/etc/letsencrypt/live/{{ server_name }}/fullchain.pem
  register: ssl_chain_file

- name: Check SSL Priv Key File Exists
  when: ssl_enabled
  stat: path=/etc/letsencrypt/live/{{ server_name }}/privkey.pem
  register: ssl_priv_file

- name: Setup SSL
  when:
    - ssl_enabled
    - ssl_chain_file.stat.islnk is not defined or ssl_priv_file.stat.islnk is not defined
  include: setup-ssl.yml

#This will setup the site configuration if ssl is not enabled or if its already set up
- when: not ssl_enabled or (ssl_chain_file.stat.islnk is defined and ssl_priv_file.stat.islnk is defined)
  include: setup-site.yml
