---

- name: Check if apache exists
  stat: path=/etc/apache2
  register: apache_exists

- name: Stop apache
  when: apache_exists.stat.isdir is defined and apache_exists.stat.isdir
  systemd: name=apache2 state=stopped
  ignore_errors: true

- name: Remove apache
  when: apache_exists.stat.isdir is defined and apache_exists.stat.isdir
  apt: name={{ item }} state=absent purge=yes autoremove=yes autoclean=yes
  with_items:
    - apache2
    - apache2-utils
    - apache2.2-bin
    - apache2-common

- name: Remove remaining apache folders and files
  when: apache_exists.stat.isdir is defined and apache_exists.stat.isdir
  file: path={{ item }} state=absent
  with_items:
    - /usr/sbin/apache2
    - /usr/lib/apache2
    - /etc/apache2
    - /usr/share/man/man8/apache2.8.gz
