---

- include_vars: file="../../php/defaults/main.yml"

- name: Add {{ server_name }} Config
  template: src={{ server_name }}.conf dest=/etc/nginx/sites-available/{{ server_name }} owner=root group=root

- name: Enable Site Config
  file: src=/etc/nginx/sites-available/{{ server_name }} dest=/etc/nginx/sites-enabled/{{ server_name }} state=link
  notify:
    - Reload Nginx
