---

- name: Execute Playbook
  hosts: local
  user: root
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
    - name: 'install aptitude'
      raw: sudo apt-get -y install aptitude
  roles:
    - apt
    - users
    - ufw
    - nginx
    - php
    - node
    - git
    - ssl
    - crontab
