---

- name: Create Project Folder
  file: path={{ project_root }} state=directory mode=0775 owner=www-data group=www-data

- name: Setup Github Repo
  git:  repo={{ github_repo }}
        dest={{ project_root }}
        accept_hostkey=yes
        key_file="/root/.ssh/{{ server_name }}"
  register: gitrepoinstalled
  notify:
    - Reload Nginx

- name: Add .env file
  when: gitrepoinstalled|success
  template: src=.env dest={{ project_root }}/.env owner=www-data group=www-data
  notify:
    - Reload Nginx

- name: Setup git config email
  when: gitrepoinstalled|success
  git_config:
    name: user.email
    repo: "{{ project_root }}"
    scope: local
    value: '{{ github_config_email }}'

- name: Setup git config name
  when: gitrepoinstalled|success
  git_config:
    name: user.name
    repo: "{{ project_root }}"
    scope: local
    value: '{{ github_config_name }}'

- name: Set Folder/File Owner and Group
  when: gitrepoinstalled|success
  file: path={{ project_root }} owner=www-data group=www-data recurse=yes
