---

- name: Creates ssh directory
  file: path=/root/.ssh state=directory owner=root group=root

- name: Add SSH public key file
  copy: src="{{ server_name}}.pub"
        dest=/root/.ssh/{{ server_name}}.pub
        mode=0644
        owner=root
        group=root

- name: Add SSH private key file
  copy: src="{{ server_name}}"
        dest=/root/.ssh/{{ server_name }}
        mode=0600
        owner=root
        group=root
