---

- name: Create Project Folder
  file: path={{ project_root }} state=directory mode=0775 owner=www-data group=www-data
  # register: dir_created

# - name: Ensure directories are 0775
#   when: dir_created|success
#   command: find {{ project_root }} -type d -exec chmod -c 0775 {} \;
#   register: dirs_updated
#   changed_when: "dirs_updated.stdout != \"\""

# - name: Ensure files are 0664
#   when: dir_created|success
#   command: find {{ project_root }} -type f -exec chmod -c 0664 {} \;
#   register: files_updated
#   changed_when: "files_updated.stdout != \"\""

- name: Setup Github Repo
  # when:
  #   - dirs_updated|success
  #   - files_updated|success
  git:  repo={{ github_repo }}
        dest={{ project_root }}
        accept_hostkey=yes
        key_file="/root/.ssh/{{ server_name }}"
  # become: yes
  # become_user: {{ git_user }}
  register: gitrepoinstalled
  notify:
    - Reload Nginx

- name: Composer install
  when: gitrepoinstalled|success
  # become: yes
  # become_user: {{ git_user }}
  composer:
    command: install
    working_dir: "{{ project_root }}"
  notify:
    - Reload Nginx

- name: Add .env file
  when: gitrepoinstalled|success
  template: src=.env dest={{ project_root }}/.env owner=www-data group=www-data
  notify:
    - Reload Nginx

- name: Setup git config email
  when: gitrepoinstalled|success
  git_config:
    name: user.email
    repo: "{{ project_root }}"
    scope: local
    value: '{{ github_config_email }}'

- name: Setup git config name
  when: gitrepoinstalled|success
  git_config:
    name: user.name
    repo: "{{ project_root }}"
    scope: local
    value: '{{ github_config_name }}'

- name: Set Folder/File Owner and Group
  when: gitrepoinstalled|success
  file: path={{ project_root }} owner=www-data group=www-data recurse=yes
