---

- name: Add Node PPA
  shell: curl --silent --location https://deb.nodesource.com/setup_{{ node_version }} | bash -

- name: Install Node
  apt: pkg=nodejs state=installed update_cache=yes

- name: Install Node Global Modules
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ node_global_modules }}"
