---

- name: Start PHP-FPM
  service: name=php{{ php_version }}-fpm state=started

- name: Restart PHP-FPM
  service: name=php{{ php_version }}-fpm state=restarted

- include: ../../nginx/handlers/main.yml